"""Second try

Revision ID: 4aedf0cac2ee
Revises: c8fdeca6972e
Create Date: 2023-11-09 22:23:33.036506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aedf0cac2ee'
down_revision = 'c8fdeca6972e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('danger', sa.Column('status', sa.Integer(), nullable=True, default=0))
    op.add_column('danger', sa.Column('address', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_danger_id'), 'danger', ['id'])
    op.create_unique_constraint(op.f('uq_human_id'), 'human', ['id'])
    op.execute('''INSERT INTO human (first_name, last_name, middle_name, photo, danger_level)
    VALUES ('John', 'Doe', 'Smith', 'https://example.com/john_doe.jpg', 2);
    ''')
    op.execute('''INSERT INTO human (first_name, last_name, middle_name, photo, danger_level)
    VALUES ('Alice', 'Johnson', 'Marie', 'https://example.com/alice_johnson.jpg', 1);
    ''')
    op.execute('''INSERT INTO human (first_name, last_name, middle_name, photo, danger_level)
    VALUES ('Sarah', 'Smith', 'Anne', 'https://example.com/sarah_smith.jpg', 3);
    ''')
    op.execute('''INSERT INTO human (first_name, last_name, middle_name, photo, danger_level)
    VALUES ('Michael', 'Brown', 'James', 'https://example.com/michael_brown.jpg', 1);
    ''')
    op.execute('''INSERT INTO human (first_name, last_name, middle_name, photo, danger_level)
    VALUES ('Emily', 'Davis', 'Grace', 'https://example.com/emily_davis.jpg', 2);
    ''')
    op.execute('''INSERT INTO human (first_name, last_name, middle_name, photo, danger_level)
    VALUES ('David', 'Miller', 'John', 'https://example.com/david_miller.jpg', 1);
    ''')

    op.execute('''
            INSERT INTO danger (name, description, shots, suspenders, danger_level, address)
            VALUES ('Explosion', 'Powerful explosion with fire and smoke', ARRAY['https://example.com/explosion.jpg'], ARRAY[1, 3, 5], 5,
            'Бабочкина 5')
        ''')

    op.execute("""
            INSERT INTO danger (name, description, shots, suspenders, danger_level, address)
            VALUES ('Chemical Spill', 'Hazardous chemical spill', ARRAY['https://example.com/chemical_spill.jpg'], ARRAY[2, 4, 6], 4,
            'Бабочкина 7')
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_human_id'), 'human', type_='unique')
    op.drop_constraint(op.f('uq_danger_id'), 'danger', type_='unique')
    op.drop_column('danger', 'address')
    op.drop_column('danger', 'status')
    # ### end Alembic commands ###